apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hw-dev
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: hw-pipeline/hw-dev:latest
        ports:
        - containerPort: 8888
        resources:
          requests:
            memory: "25Mi"
            cpu: "250m"
          limits:
            memory: "150Mi"
            cpu: "500m"
      serviceAccountName: hello-world