apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hw-pullers
  namespace: hw-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- kind: ServiceAccount
  name: hello-world
  namespace: hw-dev
- kind: ServiceAccount
  name: hello-world
  namespace: hw-stage