#This manifest creates 2 basic service accounts to be used by our deployments
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world
  namespace: hw-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello-world
  namespace: hw-stage