#This is a generic ClusterIP k8s service intended to be added to with a form of ingress to allow external communication. 
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: hw-dev
spec:
  type: ClusterIP
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888 