# This file contains some basic RBAC requirements that allow this to run on k8s
# the roleBinding will also need to be changed depending on setup - as it is set up to use the internal openshift registry
# It is currently a basic set of reqs and should be tightened with refinement of the pipeline process
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hw-builder
  namespace: hw-pipeline
secrets:
 - name: hello-world-source-git-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hw-builder-image-rb
  namespace: hw-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-builder
subjects:
- kind: ServiceAccount
  name: hw-builder
  namespace: hw-pipeline